Controllers/AdminController.cs
using Courier_Management_System.Data;
using Courier_Management_System.Models;
using Courier_Management_System.Models.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Courier_Management_System.Controllers
{
    public class AdminController : Controller
    {
        private readonly CourierDbContext courierDbContext;
        public AdminController(CourierDbContext courierDbContext) 
        {
            this.courierDbContext = courierDbContext;
        }

        [HttpGet]
        public IActionResult AdminRegister()
        {
            return View();
        }
      
        [HttpPost]
        public async Task<IActionResult> AdminRegister(AddAdminModel addAdminModel)
        {
                var admin = new Admin
                {
                    AdminEmail = addAdminModel.AdminEmail,
                    AdminPassword = addAdminModel.AdminPassword,
                    AdminName = addAdminModel.AdminName
                };

               await courierDbContext.Admins.AddAsync(admin);
               await courierDbContext.SaveChangesAsync();

                return RedirectToAction("AdminsList");
        }

        [HttpGet]
        public async Task<IActionResult> AdminsList()
        {
            var adminsList = await courierDbContext.Admins.ToListAsync();
            return View(adminsList);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteAdmin(AddAdminModel adminLoginModel)
        {
            var admin = await courierDbContext.Admins.FirstOrDefaultAsync(a => a.AdminEmail == adminLoginModel.AdminEmail);

            if (admin != null)
            {
                courierDbContext.Admins.Remove(admin);
                await courierDbContext.SaveChangesAsync();
                return RedirectToAction("AdminsList");
            }

            return RedirectToAction("AdminsList");
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(AdminLoginModel loginModel)
        {
            if (ModelState.IsValid)
            {
                var admin = await courierDbContext.Admins.FirstOrDefaultAsync(a => a.AdminEmail == loginModel.AdminEmail && a.AdminPassword == loginModel.AdminPassword);

                if (admin != null)
                {
                    return RedirectToAction("Index", "Home"); //Admin panel redirect
                }
                else
                {
                    return RedirectToAction("Dashboard", "Home"); //dashboard redirect 
                }
            }
            return View(loginModel);
        }
    }
}

Controllers/HomeController.cs
using Courier_Management_System.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Courier_Management_System.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Dashboard()
        {
            return View();
        }

        public IActionResult OrderConfirmation() 
        {
            return View();
        }

        public IActionResult CustomerPanel()
        {
            return View();
        }

        public IActionResult TrackParcel()
        {
            return View();
        }

        public IActionResult AdminRegConfirmation() 
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ShipmentController.cs
using Courier_Management_System.Data;
using Courier_Management_System.Models;
using Courier_Management_System.Models.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Courier_Management_System.Controllers
{
    public class ShipmentController : Controller
    {
        private readonly CourierDbContext courierDbContext;

        public ShipmentController(CourierDbContext courierDbContext)
        {
            this.courierDbContext = courierDbContext;
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(AddShipmentViewModel addShipmentRequest)
        {
            var shipment = new Shipment()
            {
                Id = Guid.NewGuid(),
                ShipperName = addShipmentRequest.ShipperName,
                ShipperAddress = addShipmentRequest.ShipperAddress,
                ShipperEmail = addShipmentRequest.ShipperEmail,

                ReceiverName = addShipmentRequest.ReceiverName,
                ReceiverAddress = addShipmentRequest.ReceiverAddress,
                ReceiverEmail = addShipmentRequest.ReceiverEmail,

                ShipmentStatus = addShipmentRequest.ShipmentStatus,

            };

            await courierDbContext.Shipments.AddAsync(shipment);
            await courierDbContext.SaveChangesAsync();
            return RedirectToAction("ShipmentList");

        }

        [HttpGet]
        public async Task<IActionResult> ShipmentList()
        {
            var shipments= await courierDbContext.Shipments.ToListAsync();
            return View(shipments);
        }

        [HttpGet]
        public async Task<IActionResult> View(Guid Id)
        {
            var shipmentInfoAvailable = await courierDbContext.Shipments.FirstOrDefaultAsync(x => x.Id == Id);

            if(shipmentInfoAvailable != null)
            {
                var viewModel = new UpdateShipmentViewModel()
                {
                    Id = shipmentInfoAvailable.Id,
                    ShipperName = shipmentInfoAvailable.ShipperName,
                    ShipperAddress = shipmentInfoAvailable.ShipperAddress,
                    ShipperEmail = shipmentInfoAvailable.ShipperEmail,

                    ReceiverName = shipmentInfoAvailable.ReceiverName,
                    ReceiverAddress = shipmentInfoAvailable.ReceiverAddress,
                    ReceiverEmail = shipmentInfoAvailable.ReceiverEmail,

                    ShipmentStatus = shipmentInfoAvailable.ShipmentStatus,
                };
                return await Task.Run (()=> View("View", viewModel));
            }

            return RedirectToAction("ShipmentList");
        }


        [HttpPost]
        public async Task<IActionResult> View(UpdateShipmentViewModel model)
        {
            var shipments = await courierDbContext.Shipments.FindAsync(model.Id);

            if(shipments != null)
            {
                shipments.ShipperName = model.ShipperName;
                shipments.ShipperAddress = model.ShipperAddress;
                shipments.ShipperEmail = model.ShipperEmail;
                shipments.ReceiverName = model.ReceiverName;
                shipments.ReceiverAddress = model.ReceiverAddress;
                shipments.ReceiverEmail = model.ReceiverEmail;
                shipments.ShipmentStatus = model.ShipmentStatus;

               await courierDbContext.SaveChangesAsync();

                return RedirectToAction("ShipmentList");
            }
            return RedirectToAction("ShipmentList");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateShipmentViewModel model)
        {
            var shipmentInfo = await courierDbContext.Shipments.FindAsync(model.Id);

            if(shipmentInfo != null)
            {
                courierDbContext.Shipments.Remove(shipmentInfo);
                await courierDbContext.SaveChangesAsync();

                return RedirectToAction("ShipmentList");
            }
            return RedirectToAction("ShipmentList");
        }



        [HttpGet]
        public IActionResult CustomerDetails()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CustomerDetails(AddShipmentViewModel customerAddShipmentRequest)
        {
            var shipment = new Shipment()
            {
                Id = Guid.NewGuid(),
                ShipperName = customerAddShipmentRequest.ShipperName,
                ShipperAddress = customerAddShipmentRequest.ShipperAddress,
                ShipperEmail = customerAddShipmentRequest.ShipperEmail,

                ReceiverName = customerAddShipmentRequest.ReceiverName,
                ReceiverAddress = customerAddShipmentRequest.ReceiverAddress,
                ReceiverEmail = customerAddShipmentRequest.ReceiverEmail,

                ShipmentStatus = customerAddShipmentRequest.ShipmentStatus,

            };

            await courierDbContext.Shipments.AddAsync(shipment);
            await courierDbContext.SaveChangesAsync();
            return RedirectToAction("OrderConfirmation", "Home");
        }



        [HttpGet]
        public async Task<IActionResult> SearchShipment(Guid Id)
        {
          
            var shipment = await courierDbContext.Shipments.FirstOrDefaultAsync(x => x.Id == Id);

            if (shipment == null)
            {
                return NotFound();
            }

            var shipments = new List<Shipment> { shipment }; 

            return View(shipments);
        }

        public async Task<IActionResult> SearchShipmentCustomer(Guid Id)
        {

            var shipment = await courierDbContext.Shipments.FirstOrDefaultAsync(x => x.Id == Id);

            if (shipment == null)
            {
                return NotFound();
            }

            var shipments = new List<Shipment> { shipment };

            return View(shipments);
        }




    }
}

Views/Home/AdminRegConfirmation.cshtml
@{
}

<div class="text-center">
    <h1 class="display-4">Admin Registration Confirmation</h1>
    <small style="opacity:0.6">Courier Management System [Developed by Asif Zaman]</small>
    <hr />
</div>


<h2>
    Admin is successfully registered.
</h2>

<button class="btn btn-primary"><a asp-controller="Home" asp-action="Index" style="text-decoration:none;color:whitesmoke">Back To Admin Panel</a></button>

Views/Home/CustomerPanel.cshtml
@{
}

<div class="text-center">
    <h1 class="display-4">Customer Panel</h1>
    <small style="opacity:0.6">Courier Management System [Developed by Asif Zaman]</small>
    <hr />
</div>

<div style="display:grid; gap:20px">
    <a class="btn btn-outline-primary" asp-area="" asp-controller="Home" asp-action="Dashboard">Dashboard</a>
    <a class="btn btn-outline-success" asp-area="" asp-controller="Shipment" asp-action="CustomerDetails">Deliver your parcel</a>
    <a class="btn btn-outline-warning" asp-area="" asp-controller="Home" asp-action="TrackParcel">Track your parcel</a>
</div>

Views/Home/Dashboard.cshtml
@{
}

<div class="text-center">
    <h1 class="display-4">Instant Courier Service</h1>
    <small style="opacity:0.6">Courier Management System [Developed by Asif Zaman]</small>
    <hr />
</div>

<marquee style="background-color:orangered ;color:aliceblue; border-radius:10px;"><h4>Welcome to Instant Courier Service. You can place order to send a courier from any where anytime.</h4></marquee>


<br />
<br />
<br />
<h2>Why Instant Courier Service? </h2>

<ul class="list-group">
    <li class="list-group-item">Enjoy global customer flexibility</li>
    <li class="list-group-item">Customer registration is a hassle from the customer endppoint</li>
    <li class="list-group-item">Don't be registered and be secured</li>
    <li class="list-group-item">Just give us the delivery credentials to deliver the items</li>
    <li class="list-group-item">We priotize data security</li>
</ul>

<br />
<br />

<div style="margin-left:12vw">
    <div  style="display:flex; gap:100px">
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="images/cus.jpg" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">Customer Panel</h5>
                <p class="card-text">Cusotmers can easily place orders without being registered. Security is our priority </p><br />
                <a href="Home/CustomerPanel" class="btn btn-primary">Customer panel</a>
            </div>
        </div>

        <br />
        <br />

        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="images/admin.jpeg" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">Admin panel</h5>
                <p class="card-text">Admin can manage the shipments and search them by the consignment Id. Admins credentials are needed to log in</p>
                <a asp-controller="Admin" asp-action="Login"  class="btn btn-primary">Admin Panel</a>
            </div>
        </div>
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Dashboard";
       
}

<div class="text-center">
    <h1 class="display-4">Admin Panel</h1>
    <small style="opacity:0.6">Courier Management System [Developed by Asif Zaman]</small>
    <hr />

    <div style="display:grid; gap:10px;">
        <button type="button" class="btn btn-primary btn-lg"><a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Dashboard">Dashboard</a></button>
        <button type="button" class="btn btn-primary btn-lg"><a class="nav-link text-white" asp-area="" asp-controller="Shipment" asp-action="Add">Add Shipments or Customers</a></button>
        <button type="button" class="btn btn-primary btn-lg"><a class="nav-link text-white" asp-area="" asp-controller="Shipment" asp-action="ShipmentList">Manage Shipments</a></button>
        <button type="button" class="btn btn-primary btn-lg"><a class="nav-link text-white" asp-area="" asp-controller="Shipment" asp-action="ShipmentList">Search By Consignment ID</a>
            <br /><small style="opacity:0.6">[Only for the acknowledged Consignment ID]</small>
        </button>

        <br />
        <a class="btn btn-outline-danger" asp-area="" asp-controller="Admin" asp-action="AdminRegister" >Register a Admin</a>
        <a class="btn btn-outline-danger" asp-area="" asp-controller="Admin" asp-action="AdminsList"> Admins Information</a>
    </div>
   
</div>

Views/Home/OrderConfirmation.cshtml
@{
}

<div class="text-center">
    <h1 class="display-4">Order Confirmation</h1>
    <small style="opacity:0.6">Courier Management System [Developed by Asif Zaman]</small>
    <hr />
</div>

<h4>Your order is confirmed. A consignment number has been sent to your email. </h4>
<h5 style="opacity:0.6">example: 61cef7ab-05c9-4bfb-bbb5-b3d7c5f53089</h5>

<h4 >You can track your courier status with this consignment Id</h4>

<button class="btn btn-primary"><a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Dashboard">Done!</a></button>

Views/Home/TrackParcel.cshtml
@{
}

<div class="text-center">
    <h1 class="display-4">Courier Tracking Info</h1>
    <small style="opacity:0.6">Courier Management System [Developed by Asif Zaman]</small>
    <hr />
</div>

<form asp-controller="Shipment" asp-action="SearchShipmentCustomer" method="get">
    <div class="form-group">
        <label for="shipmentId">Consignment ID <small>[Enter your delivery consignment number]</small> </label>
        <input type="text" class="form-control" id="shipmentId" name="id" placeholder="6362a480-c915-4d38-a246-ce30697a81f1">
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Search</button>
     <a asp-action="CustomerPanel" asp-controller="Home" class="btn btn-primary">Back to Customer panel</a>
</form>